---
title: "Replication of Evidence of Serial Processing in Visual Word Recognition by White, Palmer and Boynton (2018, Psychological Science)"
author: "Philip Hernandez (philipah@stanford.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->


##Introduction
My research interests lie in studying adult learning in the sciences, from the undergraduate sciences through medical school, especially where learning still takes place in lecture halls. However, I’m also interested in what neuroscience and the cognitive sciences can bring to this realm and what can be learned using these populations of post-secondary students. This study, though nominally part of this body of research does concern itself with the population I am interested in.  In addition, I feel that in replicating this study, I would not only be able to hone skills necessary for processing data from intervention studies, but I also find the underlying idea of parallel or serial processing important to consider, even if the study is far removed from application in the classroom setting.   

The experiment involves participants watching a screen on which stimuli are presented. The stimuli will involve the presentation of fixation crosses, precues consisting of words and dashes to the right and left of the fixation cross, words/word-masks, and word pairs in a rapid-serial-visual-presentation, followed by a post-cue consisting of words, dashes to the right/left of a fixation cross .  The word pairs may be in the same color or different colors and the interstimulus interval would be an aspect that could be manipulated. Some feedback from participant responses would initially be used to determine participants color detection threshold and interstimulus intervals would be adjusted to keep subject performance on single-task semantic performance below a threshold which would allow them to process both words. 

One of the main challenges would be equipment, as eye-trackers were used in the experimental set-up to determine whether gaze was fixed on the fixation cross. Eye-trackers are not usually part of online study populations such as those in MTurk. However, given that only 5.9% of trials were discarded in the paper, it may be possible to do the study without using eye-tracking, which would remove some of the technical difficulty. The Challenges include recruitment, programming stimuli and making sure that the program responds to participants responses so that the appropriate inter-stimulus interval is used. 



##Methods

###Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

###Planned Sample

Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any.

###Materials

All materials - can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

###Procedure	

Can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

###Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

###Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


##Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
###Data Preparation

####Load Relevant Libraries and Functions

####Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

###Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
